# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DateTextField' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DateTextField
pod 'SwiftyJSON', '~> 4.0'

  target 'DateTextFieldTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DateTextFieldUITests' do
    # Pods for testing
  end

end
